"use client";

import { useState } from "react";

export default function ItineraryCard({ itinerary }: any) {
    const [selectedDay, setSelectedDay] = useState(0);

    if (!itinerary) {
        return (
            <div className="bg-white p-6 rounded-2xl shadow-md mt-6">
                <p className="text-gray-500">Generate a trip to see itinerary</p>
            </div>
        );
    }

    const dayPlans = itinerary.itinerary || [];
    const currentDay = dayPlans[selectedDay];

    return (
        <div className="bg-white p-6 rounded-2xl shadow-md mt-6">

            {/* Header */}
            <h1 className="text-4xl font-bold mb-2">
                AI Trip Planner
            </h1>
            <p className="text-gray-500 mb-6">
                Your personalized itinerary generated by AI
            </p>

            {/* Day Buttons */}
            <div className="flex gap-4 flex-wrap mb-6">
                {dayPlans.map((day: any, index: number) => (
                    <button
                        key={index}
                        onClick={() => setSelectedDay(index)}
                        className={`px-6 py-3 rounded-xl font-semibold ${selectedDay === index
                            ? "bg-purple-600 text-white"
                            : "bg-gray-100"
                            }`}
                    >
                        {day.day}
                    </button>
                ))}
            </div>

            {/* Selected Day Plan */}
            {currentDay && (
                <div className="bg-purple-50 p-6 rounded-2xl mb-6">
                    <h2 className="text-3xl font-bold text-purple-700 mb-4">
                        {currentDay.day} Plan
                    </h2>

                    {currentDay.activities.map(
                        (activity: any, index: number) => (
                            <div
                                key={index}
                                className="bg-white rounded-xl p-5 shadow-sm mb-4"
                            >
                                <h3 className="text-2xl font-bold">
                                    {activity.time}
                                </h3>

                                <p className="text-lg mt-2">
                                    {activity.place}
                                </p>

                                <p className="text-gray-600 mt-2">
                                    Transport: {activity.transport}
                                </p>

                                <p className="text-gray-600">
                                    Food: {activity.food}
                                </p>

                                <p className="text-purple-600 font-bold mt-2">
                                    {activity.cost}
                                </p>
                            </div>
                        )
                    )}
                </div>
            )}

            {/* Hotels */}
            <div className="bg-blue-50 p-6 rounded-2xl mb-6">
                <h2 className="text-2xl font-bold text-blue-700 mb-4">
                    Recommended Hotels
                </h2>

                {itinerary?.hotels?.map(
                    (hotel: any, index: number) => (
                        <div
                            key={index}
                            className="bg-white p-4 rounded-xl shadow-sm mb-3"
                        >
                            <h3 className="font-semibold text-lg">
                                {hotel.name}
                            </h3>

                            <p className="text-green-600 font-medium">
                                {hotel.price}
                            </p>

                            <p className="text-sm text-gray-600 mt-1">
                                Rating: {hotel.rating || "4.5/5"}
                            </p>

                            <p className="text-sm text-gray-600 mt-1">
                                {hotel.description || "Comfortable stay suited for your trip."}
                            </p>

                            <p className="text-xs text-gray-500 mt-2">
                                {hotel.match_reason || "Good match for your selected budget."}
                            </p>
                        </div>
                    )
                )}
            </div>

            {/* Transport */}
            <div className="bg-green-50 p-6 rounded-2xl mb-6">
                <h2 className="text-2xl font-bold text-green-700 mb-4">
                    Transport Options
                </h2>

                {itinerary?.transport_options?.map(
                    (transport: any, index: number) => (
                        <p key={index} className="mb-2">
                            • {transport}
                        </p>
                    )
                )}
            </div>

            {/* Budget */}
            <div className="bg-yellow-50 p-6 rounded-2xl mb-6">
                <h2 className="text-2xl font-bold text-yellow-700 mb-4">
                    Recommended Budget
                </h2>

                <p className="text-2xl font-bold">
                    {itinerary?.recommended_budget}
                </p>
            </div>

            {/* Travel Tips */}
            <div className="bg-purple-50 p-6 rounded-2xl">
                <h2 className="text-2xl font-bold text-purple-700 mb-4">
                    Smart Travel Tips
                </h2>

                {itinerary?.travel_tips?.map(
                    (tip: string, index: number) => (
                        <p key={index} className="mb-2">
                            • {tip}
                        </p>
                    )
                )}
            </div>
        </div>
    );
}